apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: automation-controller
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/Yuri-Fernando/enterprise-cloud-automation-platform.git
    targetRevision: main
    path: helm/automation-controller
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
